host: ENC[AES256_GCM,data:NRfSM5YU1964,iv:2CBIF1+lreSNvYbFo9pHM12u8uSl89XpfYJz8RmjXtQ=,tag:Vnb7ua61bidnWqmGKKMeYQ==,type:str]
port: ENC[AES256_GCM,data:dc81Chc=,iv:MxSkmkKXmcrFB3I6AZQ2rSuAFhS36iHo9pVSr5ARIXM=,tag:Ov+Xwa8SFijTRA8abhlLbA==,type:int]
password: ENC[AES256_GCM,data:z7NPPgfIRyARoNAte6Fds0prgEOhKnFWOeCLY0jqk4dz29f65s+6W4KAIaM=,iv:c+z72wqq1CwtV1HIbbidmvxe4+KXCq+i7oHPVE5Koeo=,tag:QkQzbsvXuZFWpqhfOgfSyw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/minecraft-server-tiede/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-07-03T02:54:47Z'
        enc: CiQArht5vclq1c0OI9fIx0DbQa7TrDZe/f0duEsv8BVnLwwuEZkSSQB7xAehNaQhpqUVVYt6Uxrdt0LNUSJ14nmCP17TkWHI6fK21HbwPVyB4rm7HdynU2gG+Sg0lN9+81mUxW/lhWeD0TuFwLMOn58=
    azure_kv: []
    lastmodified: '2020-07-03T02:54:48Z'
    mac: ENC[AES256_GCM,data:2gqiMefC+7oADSuxwaC9Mw1wIpgAWhqjkRuIhL2+7TSBQUrj7EiRnPH6nMGdTxk7OVgQZCRhsR37/Q+OMQvE3hCTzMgLM/L/1bG5huJmifp3LRonEYf23phH8LVqF1niA8kOPUBpaFCmhig4N5TQwoWuHsXxDyd7/rFuN0Qjlpc=,iv:iEkoSCJYLe9UXDBTEc/93kxA8sKT24ymJAJIbbL0BoM=,tag:qXqE//aBoBVYULaiLRgGxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
