host: ENC[AES256_GCM,data:aMk/LO4t8Bax,iv:X3reaNZxOAl5YovcqptguO7mylBpBUrASNVpjMKlKiw=,tag:wOQqcI6y3SVLXLakul+oUA==,type:str]
port: ENC[AES256_GCM,data:oW1v1KY=,iv:WdHRKkiMBP36yxmKPbyN7VHgv3v63wYwVJAzlqIvsAU=,tag:eYrpSEwJAw5eZvylr5M6FQ==,type:int]
password: ENC[AES256_GCM,data:EW/NaqEesLt2zLNzF15o+D5bl6+kQzLyqY9KSAMnmAOL8Oq6D+BfnJGy2PM=,iv:5yTG0xmMhbChZ2qzVEUKQYunH2oSq68GYzXQ5piA2a0=,tag:dr2uEFd4nrSgB+QSc5nerA==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/minecraft-server-tiede/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-06-23T02:36:19Z'
        enc: CiQArht5vXCzPupEFfEtTf5LngjNxC4XyiC9MbN9eQUDMOj+RRQSSQB7xAeha44P6bwFaz/VkjEFzA0oqVYPktNuu30iO4DgaGgGYXgdn4f13ghQ7Ftrnv8/2OgnxqRCXX6GKPatYfbsG28HxaaJnlQ=
    azure_kv: []
    lastmodified: '2020-06-23T02:36:19Z'
    mac: ENC[AES256_GCM,data:bLOd0UuqVJ4ypmh7NGajjoCD126BQ+y86Vx8uGImxqTcZXUOXzWjHi8ntCGXi1wwA5LQSqROK6gsNrUc3d4pi6DOO6AiNSHyeN8MWCHwTZTg2wtgivTXnFmx2h2IeKvUhvlVZOgLWM3Z9KoxQWwkuvQQymVgGTjY2e7KlzyNQMw=,iv:AUm+xpmNi1hrOHiXwFqYoHhKil6g7rZG8RFG55fzlkw=,tag:xwk4QEu+BKM0TosPgCRnyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
